// netlify/functions/_countries.js
// Source de vérité des pays / prix CÔTÉ SERVEUR.
// Le front affiche les mêmes infos pour l'UI, mais c'est CE fichier qui fait foi
// au moment de créer un paiement, pour qu'un client ne puisse pas changer un prix
// en modifiant le code JavaScript dans son navigateur.

const COUNTRIES = [
  { code:'fr', name:'France', flag:'🇫🇷', region:'Europe', tempPrice:5000, monthlyPrice:17000 },
  { code:'uk', name:'Royaume-Uni', flag:'🇬🇧', region:'Europe', tempPrice:4000, monthlyPrice:15000 },
  { code:'de', name:'Allemagne', flag:'🇩🇪', region:'Europe', tempPrice:3500, monthlyPrice:12000 },
  { code:'es', name:'Espagne', flag:'🇪🇸', region:'Europe', tempPrice:3500, monthlyPrice:12000 },
  { code:'it', name:'Italie', flag:'🇮🇹', region:'Europe', tempPrice:3500, monthlyPrice:12000 },
  { code:'pt', name:'Portugal', flag:'🇵🇹', region:'Europe', tempPrice:3000, monthlyPrice:10000 },
  { code:'be', name:'Belgique', flag:'🇧🇪', region:'Europe', tempPrice:3500, monthlyPrice:12000 },
  { code:'nl', name:'Pays-Bas', flag:'🇳🇱', region:'Europe', tempPrice:3500, monthlyPrice:12000 },
  { code:'ch', name:'Suisse', flag:'🇨🇭', region:'Europe', tempPrice:4000, monthlyPrice:15000 },
  { code:'se', name:'Suède', flag:'🇸🇪', region:'Europe', tempPrice:3000, monthlyPrice:10000 },
  { code:'no', name:'Norvège', flag:'🇳🇴', region:'Europe', tempPrice:3000, monthlyPrice:10000 },
  { code:'dk', name:'Danemark', flag:'🇩🇰', region:'Europe', tempPrice:3000, monthlyPrice:10000 },
  { code:'fi', name:'Finlande', flag:'🇫🇮', region:'Europe', tempPrice:3000, monthlyPrice:10000 },
  { code:'pl', name:'Pologne', flag:'🇵🇱', region:'Europe', tempPrice:2500, monthlyPrice:9000 },
  { code:'ro', name:'Roumanie', flag:'🇷🇴', region:'Europe', tempPrice:2500, monthlyPrice:9000 },
  { code:'ua', name:'Ukraine', flag:'🇺🇦', region:'Europe', tempPrice:2000, monthlyPrice:8000 },
  { code:'ru', name:'Russie', flag:'🇷🇺', region:'Europe', tempPrice:2000, monthlyPrice:8000 },
  { code:'gr', name:'Grèce', flag:'🇬🇷', region:'Europe', tempPrice:2500, monthlyPrice:9000 },
  { code:'at', name:'Autriche', flag:'🇦🇹', region:'Europe', tempPrice:3500, monthlyPrice:12000 },
  { code:'cz', name:'Tchéquie', flag:'🇨🇿', region:'Europe', tempPrice:2500, monthlyPrice:9000 },
  { code:'us', name:'États-Unis', flag:'🇺🇸', region:'Amériques', tempPrice:4000, monthlyPrice:15000 },
  { code:'ca', name:'Canada', flag:'🇨🇦', region:'Amériques', tempPrice:3000, monthlyPrice:10000 },
  { code:'mx', name:'Mexique', flag:'🇲🇽', region:'Amériques', tempPrice:2500, monthlyPrice:9000 },
  { code:'br', name:'Brésil', flag:'🇧🇷', region:'Amériques', tempPrice:2500, monthlyPrice:9000 },
  { code:'ar', name:'Argentine', flag:'🇦🇷', region:'Amériques', tempPrice:2000, monthlyPrice:8000 },
  { code:'co', name:'Colombie', flag:'🇨🇴', region:'Amériques', tempPrice:2000, monthlyPrice:8000 },
  { code:'cl', name:'Chili', flag:'🇨🇱', region:'Amériques', tempPrice:2000, monthlyPrice:8000 },
  { code:'pe', name:'Pérou', flag:'🇵🇪', region:'Amériques', tempPrice:2000, monthlyPrice:8000 },
  { code:'in', name:'Inde', flag:'🇮🇳', region:'Asie', tempPrice:1500, monthlyPrice:8000 },
  { code:'cn', name:'Chine', flag:'🇨🇳', region:'Asie', tempPrice:2000, monthlyPrice:9000 },
  { code:'jp', name:'Japon', flag:'🇯🇵', region:'Asie', tempPrice:3000, monthlyPrice:12000 },
  { code:'kr', name:'Corée du Sud', flag:'🇰🇷', region:'Asie', tempPrice:3000, monthlyPrice:12000 },
  { code:'id', name:'Indonésie', flag:'🇮🇩', region:'Asie', tempPrice:1500, monthlyPrice:8000 },
  { code:'ph', name:'Philippines', flag:'🇵🇭', region:'Asie', tempPrice:1500, monthlyPrice:8000 },
  { code:'vn', name:'Vietnam', flag:'🇻🇳', region:'Asie', tempPrice:1500, monthlyPrice:8000 },
  { code:'th', name:'Thaïlande', flag:'🇹🇭', region:'Asie', tempPrice:2000, monthlyPrice:8000 },
  { code:'my', name:'Malaisie', flag:'🇲🇾', region:'Asie', tempPrice:2000, monthlyPrice:8000 },
  { code:'pk', name:'Pakistan', flag:'🇵🇰', region:'Asie', tempPrice:1500, monthlyPrice:8000 },
  { code:'bd', name:'Bangladesh', flag:'🇧🇩', region:'Asie', tempPrice:1500, monthlyPrice:8000 },
  { code:'sa', name:'Arabie Saoudite', flag:'🇸🇦', region:'Asie', tempPrice:3000, monthlyPrice:12000 },
  { code:'ae', name:'Émirats Arabes', flag:'🇦🇪', region:'Asie', tempPrice:3500, monthlyPrice:14000 },
  { code:'tr', name:'Turquie', flag:'🇹🇷', region:'Asie', tempPrice:2000, monthlyPrice:8000 },
  { code:'il', name:'Israël', flag:'🇮🇱', region:'Asie', tempPrice:3000, monthlyPrice:12000 },
  { code:'kz', name:'Kazakhstan', flag:'🇰🇿', region:'Asie', tempPrice:2000, monthlyPrice:8000 },
  { code:'ng', name:'Nigeria', flag:'🇳🇬', region:'Afrique', tempPrice:2000, monthlyPrice:8000 },
  { code:'gh', name:'Ghana', flag:'🇬🇭', region:'Afrique', tempPrice:2500, monthlyPrice:8000 },
  { code:'sn', name:'Sénégal', flag:'🇸🇳', region:'Afrique', tempPrice:1500, monthlyPrice:8000 },
  { code:'ci', name:"Côte d'Ivoire", flag:'🇨🇮', region:'Afrique', tempPrice:1500, monthlyPrice:8000 },
  { code:'cm', name:'Cameroun', flag:'🇨🇲', region:'Afrique', tempPrice:1500, monthlyPrice:8000 },
  { code:'ke', name:'Kenya', flag:'🇰🇪', region:'Afrique', tempPrice:2000, monthlyPrice:8000 },
  { code:'za', name:'Afrique du Sud', flag:'🇿🇦', region:'Afrique', tempPrice:2500, monthlyPrice:9000 },
  { code:'eg', name:'Égypte', flag:'🇪🇬', region:'Afrique', tempPrice:2000, monthlyPrice:8000 },
  { code:'ma', name:'Maroc', flag:'🇲🇦', region:'Afrique', tempPrice:2000, monthlyPrice:8000 },
  { code:'dz', name:'Algérie', flag:'🇩🇿', region:'Afrique', tempPrice:2000, monthlyPrice:8000 },
  { code:'tn', name:'Tunisie', flag:'🇹🇳', region:'Afrique', tempPrice:2000, monthlyPrice:8000 },
  { code:'bj', name:'Bénin', flag:'🇧🇯', region:'Afrique', tempPrice:1500, monthlyPrice:8000 },
  { code:'tg', name:'Togo', flag:'🇹🇬', region:'Afrique', tempPrice:1500, monthlyPrice:8000 },
  { code:'ml', name:'Mali', flag:'🇲🇱', region:'Afrique', tempPrice:1500, monthlyPrice:8000 },
  { code:'bf', name:'Burkina Faso', flag:'🇧🇫', region:'Afrique', tempPrice:1500, monthlyPrice:8000 },
  { code:'tz', name:'Tanzanie', flag:'🇹🇿', region:'Afrique', tempPrice:2000, monthlyPrice:8000 },
  { code:'ug', name:'Ouganda', flag:'🇺🇬', region:'Afrique', tempPrice:2000, monthlyPrice:8000 },
  { code:'et', name:'Éthiopie', flag:'🇪🇹', region:'Afrique', tempPrice:2000, monthlyPrice:8000 },
  { code:'au', name:'Australie', flag:'🇦🇺', region:'Océanie', tempPrice:4000, monthlyPrice:15000 },
  { code:'nz', name:'Nouvelle-Zélande', flag:'🇳🇿', region:'Océanie', tempPrice:4000, monthlyPrice:15000 },
];

const COUNTRY_SMSPVA = {
  fr:'fr', uk:'gb', de:'de', es:'es', it:'it',
  pt:'pt', be:'be', nl:'nl', ch:'ch',
  se:'se', no:'no', dk:'dk', fi:'fi', pl:'pl',
  ro:'ro', ua:'ua', ru:'ru', gr:'gr', at:'at',
  cz:'cz', us:'us', ca:'ca', mx:'mx', br:'br',
  ar:'ar', co:'co', cl:'cl', pe:'pe', in:'in',
  cn:'cn', jp:'jp', kr:'kr', id:'id', ph:'ph',
  vn:'vn', th:'th', my:'my', pk:'pk', bd:'bd',
  sa:'sa', ae:'ae', tr:'tr', il:'il', kz:'kz',
  ng:'ng', gh:'gh', sn:'sn', ci:'ci', cm:'cm',
  ke:'ke', za:'za', eg:'eg', ma:'ma', dz:'dz',
  tn:'tn', bj:'bj', tg:'tg', ml:'ml', bf:'bf',
  tz:'tz', ug:'ug', et:'et', au:'au', nz:'nz'
};

module.exports = { COUNTRIES, COUNTRY_SMSPVA };
