[build]
  publish = "."
  functions = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000"
    Referrer-Policy = "strict-origin-when-cross-origin"

[functions."refresh-availability"]
  schedule = "0 0,12 * * *"

[functions."refresh-prices"]
  schedule = "0 */3 * * *"
